### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DonalDuck004** [DonalDuck004/ApexProSnake#1]
- [x] Improve image generation without capturing rendered control, dropping System.Drawining dependency :D
- [x] Remove 93-97 lines
- [x] Use unsafe stack allocated buffer/allocate once a heap buffer when creating game screenshot
- [x] Create API class and object mapping
- [ ] Error handling(?)
- [ ] Add shortcut to reset the game
- [x] Remove debug proxy
- [ ] Try to remove black rectangles/use a single color brush/xaml resource style in order to reduce memory usage
